### ISSUE TITLE
Assignment 1

### ISSUE THREAD

**Issue by ANU4247** [Jay-study-nildana/TutoringTrainingStudents#151]
Assignment 1

[Assignment 1 CSS Breakfast Places in Mumbai](https://github.com/Jay-study-nildana/TutoringTrainingStudents/discussions/80)

_Originally posted by @Jay-study-nildana in https://github.com/Jay-study-nildana/TutoringTrainingStudents/discussions/126#discussioncomment-5462612_

Is not working Solution

**Comment by ANU4247** [comment]
Hello Everyone,

Here is the one That has a working Solution

Here the 1st Assignment.
Here is my work on Codepen for Assignment-1 using HTML and CSS only (no bootstrap).

Codepen link: https://codepen.io/skilledcoder07/pen/OJBNzLo?editors=1100

I tried my level best to make it as it shown in reference model given by Edureka and managed to build it somewhat of 90% (i realised after submission).

Don't use the footer Section i used in this page i.e, for showcase purposes.

Issues that to be fixed after i realised are : to make it as checkbox type in Cuisine section, & some padding issues according to screen size is given different by e! , so it can be optmised....

[Note : i'm not in favor of copy&paste, it's for ur own good (it's a request to everyone(beginner one's) to go through all the code read & review and search it online if not understanding anything and learn it and make it on ur own atleast once (if having time) ),
For reference/study use MDN Docs: https://developer.mozilla.org/en-US/ ]

Designs(try to use these for reference model for Assignment1)

    Desktop Design Link - https://xd.adobe.com/view/2409336a-0d1e-4f89-9b6c-1f9d1da0f2db-715a/screen/dddcd560-382b-4412-a00b-c5edb322b69f/specs/

2.Msite Design Link (for mobile) - https://xd.adobe.com/view/2409336a-0d1e-4f89-9b6c-1f9d1da0f2db-715a/screen/f3dd9675-74e2-4c99-9671-18714c4e0492/specs/

Platforms
All Platform - Desktop, Mobile Website, Tablet (Note: i made it resposive for all device but need little bit of optmisation , later it can be done, if have ample amount of time).

I also made a bootstraped one (it is inspired and thanks to @shaikhanis ) please check it out here : https://codepen.io/skilledcoder07/pen/ExdVawR (responsive).

open for suggestions and reviews.

Thanks and Regards
Anupam Sinha.

**Comment by Jay-study-nildana** [comment]
@ANU4247 

Thanks for sharing and explanation. I have linked this thread to the main discussion as well. 

https://github.com/Jay-study-nildana/TutoringTrainingStudents/discussions/80

Jay.
see my memes here, https://imgflip.com/user/codingtutorjay
join my open source community, here, https://github.com/BigbabeeSmallbabee
insta and twitter and other things, available on my github profile.
