### ISSUE TITLE
Local Storage

### ISSUE THREAD

**Issue by SeshuYaswanth** [Jay-study-nildana/TutoringTrainingStudents#65]
sir can you explain about how to access the Local Storage in JavaScript?

Thanks,
Seshu

**Comment by EmmanuelMoshood** [comment]
> sir can you explain about how to access the Local Storage in JavaScript?
> 
> Thanks, Seshu

I also have the same issue. Please give examples.

**Comment by Jay-study-nildana** [comment]
@SeshuYaswanth 

No problem. let me look into it.

**Comment by Jay-study-nildana** [comment]
@SeshuYaswanth 

(note: this answered was generated using AI)

```
//local storage javascript

var myStorage = window.localStorage;

//set item
myStorage.setItem('name', 'John');

//get item

var name = myStorage.getItem('name');

//remove item

myStorage.removeItem('name');

//clear all items

myStorage.clear();

//session storage javascript

var myStorage = window.sessionStorage;

//set item

myStorage.setItem('name', 'John');

//get item

var name = myStorage.getItem('name');

//remove item

myStorage.removeItem('name');

//clear all items

myStorage.clear();
```

Hopefully this helps you. if you have a specific question, or you are working on a project and want more details, please let me know.

Thanks.

Jay.

**Comment by SeshuYaswanth** [comment]
> @SeshuYaswanth
> 
> (note: this answered was generated using AI)
> 
> ```
> //local storage javascript
> 
> var myStorage = window.localStorage;
> 
> //set item
> myStorage.setItem('name', 'John');
> 
> //get item
> 
> var name = myStorage.getItem('name');
> 
> //remove item
> 
> myStorage.removeItem('name');
> 
> //clear all items
> 
> myStorage.clear();
> 
> //session storage javascript
> 
> var myStorage = window.sessionStorage;
> 
> //set item
> 
> myStorage.setItem('name', 'John');
> 
> //get item
> 
> var name = myStorage.getItem('name');
> 
> //remove item
> 
> myStorage.removeItem('name');
> 
> //clear all items
> 
> myStorage.clear();
> ```
> 
> Hopefully this helps you. if you have a specific question, or you are working on a project and want more details, please let me know.
> 
> Thanks.
> 
> Jay.

**Comment by SeshuYaswanth** [comment]
@Jay-study-nildana 
Thanks sir
