### ISSUE TITLE
Issue in Recursion Function

### ISSUE THREAD

**Issue by sukhepadda** [Jay-study-nildana/TutoringTrainingStudents#69]
Hi jay, 

I am doing some js in freecodecamp and there is one function i cannot get it, so can you pls explain me whats happening in this function(explain else part) (Replace Loops using Recursion) 

```
function multiply(arr, n) { 
	if (n <= 0) { 
		return 1; 
	} else { 
		return multiply(arr, n - 1) * arr[n - 1]; 
	}
}
```

thanks.

**Comment by Jay-study-nildana** [comment]
@sukhepadda 

It is like for loop five times. 

```
let arr = [1,2,3,4,5];

let result = multiply(arr,arr.length);
```

here, length is 5, so loop will happen 5 times. all 5 numbers will be multiplied. 

so, output will be,

```
120
```

**Comment by shaikhanis** [comment]
```
function multiply(n) { 
	if (n == 0) { 
		return 1; 
	} else { 
		return n * multiply(n-1); 
	}
}
// let arr = [1,2,3,4,5]; 

let result = multiply(5);
console.log(result);
```

**Comment by Jay-study-nildana** [comment]
@shaikhanis 

if possible, add an explanation about what your code is doing.

**Comment by Jay-study-nildana** [comment]
@sukhepadda 

also, if you are new to markdown, I have a short video on my YouTube channel. check it out.

https://youtu.be/B-tEeGhUX80

Thanks

Jay
