### ISSUE TITLE
Nasa project not working

### ISSUE THREAD

**Issue by gita11** [Jay-study-nildana/TutoringTrainingStudents#70]

**Comment by Jay-study-nildana** [comment]
@gita11 

you created the issue in the wrong repository. please use the repository

https://github.com/Jay-study-nildana/TutoringTrainingStudents

for asking doubts :)

**Comment by Jay-study-nildana** [comment]
but, anyway, I have put your issue/doubt in the correct repository. So, reply here only if you want more help with the code.

**Comment by Jay-study-nildana** [comment]
@gita11 

closing this for now. if issue still exists, feel free to reopen or create a new thread.
