### ISSUE TITLE
working on add a display history feature to a simple calculator project

### ISSUE THREAD

**Issue by EmmanuelMoshood** [Jay-study-nildana/TutoringTrainingStudents#71]
Code pen: https://codepen.io/moshnuel/pen/qByyYPe
GitHub: https://github.com/EmmanuelMoshood/50-js-projects/tree/N01CalcApp

I got stuck trying to add a display history feature. Please check it out and I will appreciate your insight on how to get this feature working.

**Comment by Jay-study-nildana** [comment]
@EmmanuelMoshood 

I personally wont' be able to look into this, but, hopefully other students will help you out. 

Usually, when something is not working, it is a good idea for you to point out specific sections of the code that you are working on and is not working. Even if somebody wants to help you, like other students, they won't have the time or the patience to look at your entire project and help you.

But, if you say

1. exactly which file
1. exactly which line number
1. errors you are getting
1. also put code snippets 

other developers will be able to jump in. this is the standard procedure when asking for help.  

Remember, there are always people willing to help. But, you must make an effort to make it easy for them to help you.

**Comment by Jay-study-nildana** [comment]
and, as I mentioned in the other thread, 'don't get hung up on this'. move on to other projects. 

return to this bug/issue after some time :) in software development, and as a first time developer remember that software development is a cycle.

1. we build things.
2. we identify bugs
3. we come to the bugs after a break
4. return to step 1.

all the best.

**Comment by Mayank-Jain-1** [comment]
@EmmanuelMoshood 

This is not a very complex problem you can use any linear data structure to fulfill this requirement like stack, queue, array etc.
A Stack is the most optimal for this kind of usage. 


>Basic definition of a stack
 A stack is a linear data structure that follows the principle of "last in, first out" (LIFO), where the most recent item added to the stack is the first one to be removed. Stacks are used for various purposes such as maintaining function call history, undo/redo operations, and implementing algorithms like depth-first search.

The idea is you keep a stack of strings which are evaluated previously and the strings of evaluated answer shown. 
Once the person clicks on the show history button. Just print all the strings from top to bottom in the stack. 

Here is an image how a stack works. In our case there will be more than just numbers being pushed and popped from the stack.

<img src="https://user-images.githubusercontent.com/99828573/217615990-c9ef4843-d4af-4a05-8b1b-e9034cc08938.png"  width="600" height="350">

**Comment by Mayank-Jain-1** [comment]
@EmmanuelMoshood

After changing a few things. 
1. The show history button was a input not button. 
2. Your code was only showing the results and not the equation in history.

This is what it looks like now. The history seems to work fine now.

https://codepen.io/Mayank-Jain-1/pen/KKBLxxr?editors=1000

**Comment by EmmanuelMoshood** [comment]
> @EmmanuelMoshood
> 
> This is not a very complex problem you can use any linear data structure to fulfill this requirement like stack, queue, array etc. A Stack is the most optimal for this kind of usage.
> 
> > Basic definition of a stack
> > A stack is a linear data structure that follows the principle of "last in, first out" (LIFO), where the most recent item added to the stack is the first one to be removed. Stacks are used for various purposes such as maintaining function call history, undo/redo operations, and implementing algorithms like depth-first search.
> 
> The idea is you keep a stack of strings which are evaluated previously and the strings of evaluated answer shown. Once the person clicks on the show history button. Just print all the strings from top to bottom in the stack.
> 
> Here is an image how a stack works. In our case there will be more than just numbers being pushed and popped from the stack.
> 
> <img alt="" width="600" height="350" src="https://user-images.githubusercontent.com/99828573/217615990-c9ef4843-d4af-4a05-8b1b-e9034cc08938.png">

yes, you're right. I thought it was actually easy too until it wasn't working. Lol
Thanks for taking the time and patience to have a look at it.

**Comment by EmmanuelMoshood** [comment]
@Mayank-Jain-1 

yes, you're right. I thought it was actually easy too until it wasn't working. Lol
Thanks for taking the time and patience to have a look at it.

**Comment by EmmanuelMoshood** [comment]
@Mayank-Jain-1 

thanks, man I see where it all went south. I had an input tag for displaying history, the function itself was right. 
I also like what you did with the history to show the expression to be evaluated as well as the result of the evaluation.
