### ISSUE TITLE
Link (Github) will not work.

### ISSUE THREAD

**Issue by AnkitSin24** [Jay-study-nildana/TutoringTrainingStudents#75]
My github path was correct but it not redirect to that page while clicking.

codepen link : https://codepen.io/AnkitSin24/pen/vYaaQLz?editors=1100

Can anybody solve  this issue.

**Comment by Jay-study-nildana** [comment]
@AnkitSin24 

that is a issue from CodePen security. Not a website problem. I was able to reach your GitHub Account, after clicking 'continue'. The code is correct ;)

**Comment by rohitchornele** [comment]
Hi Ankit,
Just a suggestion....
 
instead of this link  ==>>   
    <p> Follow Me On <a href="**https://github.com/AnkitSin24/AnkitSin24**">GitHub</a></p>

Use This ==>>
    <p> Follow Me On <a href="**https://github.com/AnkitSin24/**">GitHub</a></p>


Your Link is redirecting to your repository, not to profile if open in new tab.... and We can't open this link in Code Pen so you have to open it in new tab.

**Comment by rohitchornele** [comment]
Hi Ankit,
Just a suggestion....

instead of this link ==>>
    https://github.com/AnkitSin24/AnkitSin24

Use This ==>>
   https://github.com/AnkitSin24/

Your Link is redirecting to your repository, not to profile... if open in new tab.... and We can't open this link in Code Pen so you have to open it in new tab.

**Comment by Jay-study-nildana** [comment]
@rohitchornele 

ah. that is a good catch. redirections usually generate a security warning. nice, nice. 

Jay.

**Comment by rohitchornele** [comment]
> @rohitchornele
> 
> ah. that is a good catch. redirections usually generate a security warning. nice, nice.
> 
> Jay.


Thanks Sir.
Hope this will help @AnkitSin24

**Comment by Jay-study-nildana** [comment]
@AnkitSin24 

it will. of course it will. alright, let's close this issue as resolved. 

Jay.
