### ISSUE TITLE
Query related to API key

### ISSUE THREAD

**Issue by AnkitSin24** [Jay-study-nildana/TutoringTrainingStudents#79]
If  I  make many projects and their is a requirement of  API key.

Can we use  the same  API key for multiple projects.

**Comment by Jay-study-nildana** [comment]
@AnkitSin24 

During learning phase, it is better to use same key on all projects. 

Once learning is over, and you are building a real project, like, showcasing to your future employer, or preparing job interview, then, it is better to take a separate key for the real project, and keep it very secret.

**Comment by Mayank-Jain-1** [comment]
@AnkitSin24 

Yes, You can use the same API key for multiple projects. 
Api key are used to provide user authentication to the API service provider so they can keep track of the API usage and monitor it.
There is no problem in using same API key in different projects, but if you wan to keep track of responses on your website then you may want to use different API key to keep seperate records for projects. 

This was for the development. For production based website you should always use different API keys.
