### ISSUE TITLE
Json Data for assignment and mini project

### ISSUE THREAD

**Issue by Mayank-Jain-1** [Jay-study-nildana/TutoringTrainingStudents#85]
I am having problem making / getting right dummy data for the Movies and restaurants. If anyone has done the assignment and can share the dummy data in JSON format would be very helpful. The movie db data is not suffice.

Thank You

**Comment by Jay-study-nildana** [comment]
@Mayank-Jain-1 

Some options to try.

1. There is a sample data set available in Mongo DB, which includes both movies and restaurants. Once you have database ready, you should be able to export it. more details here, https://github.com/Jay-study-nildana/NodeJSForStudents/tree/main/MongoDB_API_CRUD_HelloWorld
1. You can also create your own random movies and restaurants using a random object generator. An example, is available here. https://github.com/Jay-study-nildana/RandomStuffDocs

As always, just wish to repeat that doing the assignments is a total waste of time, but I appreciate your persistence in doing them :)

I honestly doubt anyone else in the entire batch is doing the assignments, but, if they are, I am sure, they will reply here. Further, I have a student community, here, https://discord.gg/CVugpJRBTB . Consider joining. You might find more help there as well.

Jay.
