### ISSUE TITLE
NASA APOD XHR Project 

### ISSUE THREAD

**Issue by srinivasbk1998** [Jay-study-nildana/TutoringTrainingStudents#87]
Hi Sir,
This is my NASA APOD Project
https://codepen.io/srinivasbk1998/pen/qBMqLGG

**Comment by Jay-study-nildana** [comment]
@srinivasbk1998 

can you put your solution in this thread. This is where all students are sharing their solutions. It will be nice if you also do it there so everything is in one place. 

https://github.com/Jay-study-nildana/TutoringTrainingStudents/discussions/56

Thanks :) 

Jay
